### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ndzamboni** [ndzamboni/survey-form#1]
- [ ] Add ReadMe
- [ ] Add styling (css)
- [ ] Do some styling in JavaScript to practice DOM
- [ ] Once finished, link in the portfolio landing page
